### ISSUE TITLE
Ping?

### ISSUE THREAD

**Issue by lameventanas** [yadij/cachemgr.js#1]
Is this still maintained?
I tested it with Squid 3.5.28 and got a non-functional menu.

**Comment by yadij** [comment]
Can you explain "non-functional" please? This was developed for Squid-3.5 and I am using this now in a Squid-4 installation.

**Comment by lameventanas** [comment]
The browser requests cachemgr.js from github via http.
Github sends a 301 redirect to https, but the browser doesn't follow it.
Firefox and Chrome don't follow it, but IE will.

If I change the URLs in MGR_INDEX to protocol-absolute (eg: `//yadij.github.io/cachemgr.js/cachemgr.js` to `https://yadij.github.io/cachemgr.js/cachemgr.js`) it works in all browsers.

Perhaps it's a security policy thing, since the resources are loaded from different domains.

**Comment by yadij** [comment]
Ah. I was aware that Chrome is rejecting cross-protocol redirects. But not that it would do so despite an explicit CORS instruction to allow. Fixed now.
